#! /bin/sh

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

#█▓▒░ BASH COMPLETION
# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

#█▓▒░ SOURCE
source ~/.config_dir
source ~/.profile

#█▓▒░ MISCELLANEOUS
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

#█▓▒░ VirtualEnv
# source /home/$USER/.local/bin/virtualenvwrapper.sh
# TODO:
# /home/fox/.local/bin/virtualenvwrapper.sh: line 230: : command not found
# virtualenvwrapper.sh: There was a problem running the initialization hooks.

# If Python could not import the module virtualenvwrapper.hook_loader,
# check that virtualenvwrapper has been installed for
# VIRTUALENVWRAPPER_PYTHON= and that PATH is
# set properly.

#█▓▒░ Pyenv
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

for FN in $HOME/.dotfiles/system/bashrc.d/*.sh ; do
    source "$FN"
done

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
