#! /bin/sh

export PATH_TO_PLAYGROUND="$HOME/Playground"
export PATH_TO_PROJECTS="$HOME/Projects"
export EDITOR="code"
export WEBBROWSER="chromium"

export PATH=$PATH":$DOTFILES/scripts"           # This allows me to run my own scripts

export HISTSIZE='32768';                        # Increase Bash history size. Allow 32³ entries; the default is 500.
export HISTFILESIZE="${HISTSIZE}";
export HISTCONTROL='ignoreboth';                # Omit duplicates and commands that begin with a space from history.
export color_prompt='yes'                       # Make prompt colorfull

export MANPAGER='less -X';                      # Don’t clear the screen after quitting a manual page.

export WORKON_HOME=~/.virtualenvs

export BCKGRND='&>/dev/null & disown'
export PATH=$PATH:$DOTFILES/scripts

export LOCAL_IP=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'`

# ---------------------------------
# Don't make edits below this
[ -f "$DOTFILES/system/.exports.local" ] && source "$DOTFILES/system/.exports.local"
