#! /bin/sh
#
# GitPush - Git Helper
# Source https://github.com/iiPlasma/dots/blob/master/bin/bin/gitpush

# Check if there is unfetched online files
echo -e "Checking if there is an unfetched file from the repository"
git pull

# Add every files in the project folder
git add --all .

# Add commit message
echo "Write your commit comment!"
read COMMENT </dev/tty

# Add some details to commit message
TIME=$(date +"%a %d")
echo "${TIME}: $COMMENT"
git commit -m "${TIME}: $COMMENT"

# # Push the local files and tags to github
git push origin --tags
git push -u origin master
echo "Done!"